import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { IoHomeOutline } from "react-icons/io5";
import { IoIosContact } from "react-icons/io";
import { IoInformationCircleOutline } from "react-icons/io5";
import { FaFacebook } from "react-icons/fa";
import { FaTiktok } from "react-icons/fa";
import { BsTwitterX } from "react-icons/bs";
import { IoMdCall } from "react-icons/io";
import { MdOutlineMailOutline } from "react-icons/md";
import { CiGlobe } from "react-icons/ci";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* navbar */}

        <nav className="bg-white rounded-xl mx-[43px] my-[30] px-6 py-4 text-black text-sm md:text-base">
          <div className="container mx-auto flex items-center">
            <h1 className="text-2xl font-bold">Blood <span className="text-red-600">Bridge..</span></h1>
            <ul className="flex space-x-4 mt-2 text-center ml-[30%]" >
              <li className="flex relative group cursor-pointer"><IoHomeOutline className="mt-[2px]"/><a href="/Home" className="hover:underline">Home</a></li>
              <li className="flex"><IoInformationCircleOutline className="mt-1" /><a href="/about" className="hover:underline">About</a></li>
              <li className="flex"><IoIosContact className="mt-[3px]" /><a href="/contact" className="hover:underline">Contact</a>
              </li>
            </ul>
            <div className="flex ml-[20%] gap-2.5 text-sm md:text-base">
              <button className="px-4 py-2 font-semibold cursor-pointer">
                <span className="text-black hover:text-red-600"> log in</span>
              </button>
              <button className="relative px-4 py-2 font-semibold border-2 border-red-600 overflow-hidden
              group rounded-xl cursor-pointer">
                <span className="absolute inset-0 bg-red-600 translate-x-[-100%] group-hover:translate-x-0 
                rounded-xl transition-transform duration-400"></span>
                <span className="relative z-10 text-black group-hover:text-white transition-colors 
                duration-400"> Sign up</span>
              </button>
            </div>
          </div>
        </nav>
        {/* main content */}
        <main className="container mx-auto p-4">
          {children}
        </main>
        {/* footer */}
        <footer className=" h-[80%] bg-gray-800 w-full p-[5%] text-white ">
          <div className="ml-[10%] text-center flex space-x-[20%]">
            <div>
              <h1>BloodBridge</h1>
              <h6>Dont just recieve, Give.</h6>
              <div className="mt-7">
                <h1>Get in Touch</h1>
                <div className="flex gap-2 mt-2 items-center justify-center ml-2.5">
                  <FaFacebook />
                  <FaTiktok />
                  <BsTwitterX />
                </div>
              </div>
            </div>

            <div className="mt-7">
              <a href="/home">Home</a><span className="ml-1.5">|</span>
              <a className="ml-1.5" href="/home">About</a><span className="ml-1.5">|</span>
              <a className="ml-1.5" href="/home">Contact</a>
            </div>

            <div className="gap-2.5 mt-2.5">
              <h4 className="flex "><IoMdCall className="mt-[3.8px]"/>+234-81-57422-910</h4>
              <h4 className="flex "><MdOutlineMailOutline className="mt-[3.8px]"/>emailexample@gmail.com</h4>
              <h4 className="flex "><CiGlobe className="mt-[3.8px]"/>Engr.ibrahim street, off oghomosho</h4>
            </div>
          </div>
        </footer>
        {/* Add any additional scripts or components here */}
      </body>
    </html>
  );
}
